---
abstract: 'given a CPAN dist name, find other CPAN dists that use it'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-ReverseDependencies
requires:
  Carp: 0
  MetaCPAN::API: 0
  Moo: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/CPAN-ReverseDependencies
  repository: https://github.com/neilbowers/CPAN-ReverseDependencies.git
version: 0.01
